### ISSUE TITLE
連行移動荷重

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#104]
[サンプルデータ.zip](https://github.com/structuralengine/FrameWebforJS/files/7617247/default.zip)

**Comment by sasaco** [comment]
下図のように左上の L1 を少しずつ変えて 移動する荷重を自動作成する

![sd9](https://user-images.githubusercontent.com/4043298/143846182-19ada622-28ee-4b47-a551-13065dddb361.gif)

**Comment by Masaki-beginner** [comment]
上のL1の値を変更したところ、L1 > 0であれば正常に作動した。
L1 < 0のとき、最初の行にも加算モードが適用されるため、0 + abs(L1) となり、上のサンプルデータでは左方向に荷重が移動しない。
