### ISSUE TITLE
分布荷重以外は、円形でスケールを決める

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#108]

**Comment by Masaki-beginner** [comment]
memo

円形スケールで、決めるもの
・節点荷重の集中荷重（x, y, z）
・節点荷重のモーメント荷重（x, y, z）
・要素荷重＞集中荷重（x, y, z）

**Comment by Masaki-beginner** [comment]
部材途中モーメント荷重のsizeについてのメモ

item_child2：setScaleのタイミング（childrenが2つ）
item_child3：setSizeのタイミング→全体の最大値のratio（円形スケール）
item_child4：対になる部材途中モーメント荷重の対比？

**Comment by Masaki-beginner** [comment]
要素荷重の集中荷重・モーメントを分解した
↓参考資料↓

[要素荷重の描画形式.pptx](https://github.com/structuralengine/FrameWebforJS/files/7845438/default.pptx)
