### ISSUE TITLE
部材軸方向荷重 Axial... の矢印が デカい

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#109]
![image](https://user-images.githubusercontent.com/4043298/144358309-3d58bbe0-7849-4c73-9205-0f34ecc5ad11.png)
[2_立体骨組解析X4.zip](https://github.com/structuralengine/FrameWebforJS/files/7639027/2_.X4.zip)

**Comment by Masaki-beginner** [comment]
![image](https://user-images.githubusercontent.com/59256812/148041346-cda8db64-fb8b-4c78-b37b-156508c2ec7c.png)
次回修正点
