### ISSUE TITLE
グローバル座標の荷重gx, gy, gzの寸法線を部材に届かせたい

### ISSUE THREAD

**Issue by Masaki-beginner** [structuralengine/FrameWebforJS#114]

**Comment by Masaki-beginner** [comment]
// コードのメモ_Masaki-beginner用
    if (group.direction.includes('g')) {
      let p = [];
      const x4: number = points[4].x + L2;
      let len: number;
      if (group.direction === "gx") {
        len = -1 * Math.abs(group.nodei.x - group.nodej.x);
        if (group.P1 > 0 && group.P2 > 0) {
          if (group.nodei.x > group.nodej.x) {
            p = [ new THREE.Vector2(0, 0),
                  new THREE.Vector2(0, len) ]
          } else if (group.nodei.x < group.nodej.x) {
            p = [ new THREE.Vector2(x4, 0),
            new THREE.Vector2(x4, len)]
          } // group.nodei.x === group.nodej.x のとき線は必要ないのでelse文はなし
        } else {
          if (group.nodei.x > group.nodej.x) {
            p = [ new THREE.Vector2(x4, 0),
            new THREE.Vector2(x4, len) ]
          } else if (group.nodei.x < group.nodej.x) {
            p = [ new THREE.Vector2(0, 0),
            new THREE.Vector2(0, len) ]
          } // group.nodei.x === group.nodej.x のとき線は必要ないのでelse文はなし
        }
      } else if (group.direction === "gy") {
        len = -1 * Math.abs(group.nodei.y - group.nodej.y);
        if (group.P1 > 0 && group.P2 > 0) {
          if (group.nodei.y > group.nodej.y) {
            p = [ new THREE.Vector2(0, 0),
            new THREE.Vector2(0, len) ]
          } else if (group.nodei.y < group.nodej.y) {
            p = [ new THREE.Vector2(x4, 0),
            new THREE.Vector2(x4, len) ]
          } // group.nodei.x === group.nodej.x のとき線は必要ないのでelse文はなし
        } else {
          if (group.nodei.y > group.nodej.y) {
            p = [ new THREE.Vector2(x4, 0),
            new THREE.Vector2(x4, len) ]
          } else if (group.nodei.y < group.nodej.y) {
            p = [ new THREE.Vector2(0, 0),
            new THREE.Vector2(0, len) ]
          } // group.nodei.y === group.nodej.y のとき線は必要ないのでelse文はなし
        }
      } else if (group.direction === "gz") {
        len = -1 * Math.abs(group.nodei.z - group.nodej.z);
        if (group.P1 > 0 && group.P2 > 0) {
          if (group.nodei.z > group.nodej.z) {
            p = [ new THREE.Vector2(0, 0),
            new THREE.Vector2(0, len) ]
          } else if (group.nodei.z < group.nodej.z) {
            p = [ new THREE.Vector2(x4, 0),
            new THREE.Vector2(x4, len) ]
          } // group.nodei.x === group.nodej.x のとき線は必要ないのでelse文はなし
        } else {
          if (group.nodei.z > group.nodej.z) {
            p = [ new THREE.Vector2(x4, 0),
            new THREE.Vector2(x4, len) ]
          } else if (group.nodei.z < group.nodej.z) {
            p = [ new THREE.Vector2(0, 0),
            new THREE.Vector2(0, len) ]
          } // group.nodei.y === group.nodej.y のとき線は必要ないのでelse文はなし
        }
      }
      // ここで、線を描く
      dim.add(dim4)
    }

**Comment by yuluji** [comment]
@sasaco 
これの説明も欲しいです。
