### ISSUE TITLE
ヘッダーサイズ変更/タイプのページネーションをページのページネーションに変更/タイプの無限化

### ISSUE THREAD

**Issue by shibasaki48** [structuralengine/FrameWebforJS#125]

**Comment by mizutani488** [comment]
1.タイプのページネーションをページで使用しているページネーションに変更する。
2.タブ切り替え、アコーディオン、ページネーションのテーマ色を決めて、アクティブ時にその色を見るだけでなにをしているのかが一瞬で分かるようにする。
3.文字の大きさの統一
