### ISSUE TITLE
GridHelper の大きさをデータによって変える

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#145]
![image](https://user-images.githubusercontent.com/4043298/147645849-bb71e179-2a4a-4f6c-959a-8e5ed04b1b94.png)

**Comment by sasaco** [comment]
InfiniteGridHelper
https://github.com/Fyrestar/THREE.InfiniteGridHelper

![](https://camo.githubusercontent.com/e18c4adce64707e1d82e8ff5ef46f7ae22254f7abae1a5bd9a080f1dce43d312/68747470733a2f2f6d6576656469612e636f6d2f73686172652f496e66696e6974654772696448656c7065722e6a7067)

**Comment by Masaki-beginner** [comment]
InfiniteGridHelperのライブラリが反映できなかったため、
通常のGridHelperを変更することで対応。
