### ISSUE TITLE
断面力画面に Max, Min を表示

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#182]
![image](https://user-images.githubusercontent.com/4043298/150662802-7906a996-4500-4f97-8875-8c090d07251c.png)

**Comment by sasaco** [comment]
変位図にも

![image](https://user-images.githubusercontent.com/4043298/150662816-63184e3f-87d1-47c9-b170-7aa2fe30a176.png)

**Comment by Masaki-beginner** [comment]
高速化のためにmax_value は value_rangeの 集計結果を使って集計する
