### ISSUE TITLE
印刷可能行数の変更

### ISSUE THREAD

**Issue by mizutani488** [structuralengine/FrameWebforJS#191]

**Comment by sasaco** [comment]
[サンプル2.pdf](https://github.com/structuralengine/FrameWebforJS/files/5941350/2.pdf)

[サンプル3.pdf](https://github.com/structuralengine/FrameWebforJS/files/5941351/3.pdf)

[サンプル１.pdf](https://github.com/structuralengine/FrameWebforJS/files/5941352/default.pdf)
