### ISSUE TITLE
パネルの応力図

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#195]

**Comment by yuluji** [comment]
@sasaco 
パネルを使用した計算ですか？

**Comment by sasaco** [comment]
パネルを使用した計算について、パネルの応力図を描く機能がありません
下図のコンター図みたいなものを描けるようにしたいという話です。
![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/1c799cee-4456-4d7d-8686-d0eb2acedfe6)

**Comment by yuluji** [comment]
3Dモードで「パネル」に情報を入力すると、「パネル」の入力情報を反映した出力結果が返って来ます。
「パネル」に情報を入力した際の「部材断面力」の出力結果をもとに、パネルの四隅の色を変更して、カラーコンター図を作成してください。

**Comment by yuluji** [comment]
下記に要件をまとめました。ご不明点があれば質問してください。
[panel.pdf](https://github.com/structuralengine/FrameWebforJS/files/12449084/panel.pdf)

↓多色グラデーションの作成方法
http://systemconcept.co.jp/blog/?p=1161
