### ISSUE TITLE
データの新規更新時に前のデータが残る

### ISSUE THREAD

**Issue by mizutani488** [structuralengine/FrameWebforJS#208]
![image](https://user-images.githubusercontent.com/69898951/107183793-c1ee8a00-6a22-11eb-9179-43f6ee37b743.png)

これら1.1.1.1のデータを消したデータで再度演算しようとしたら、前のが残ってしまっている。

**Comment by mizutani488** [comment]
![image](https://user-images.githubusercontent.com/69898951/107186516-c5384480-6a27-11eb-813a-d627d6790d8c.png)
同じデータを再度ファイルを読み込むからいれたときに、計算していなくても、前回の計算データが残って印刷されてしまう。

**Comment by shibasaki48** [comment]
> ![image](https://user-images.githubusercontent.com/69898951/107183793-c1ee8a00-6a22-11eb-9179-43f6ee37b743.png)
> 
> これら1.1.1.1のデータを消したデータで再度演算しようとしたら、前のが残ってしまっている。

#257
