### ISSUE TITLE
画像保存用

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#21]

**Comment by sasaco** [comment]
<img width="1341" alt="スクリーンショット 2019-12-16 21 20 10" src="https://user-images.githubusercontent.com/4043298/70906809-a2401980-204a-11ea-8fa5-2f57b9960e0f.png">

**Comment by sasaco** [comment]
<img width="1087" alt="スクリーンショット 2019-12-16 21 21 48" src="https://user-images.githubusercontent.com/4043298/70906822-ab30eb00-204a-11ea-943f-193d8bf230d2.png">

**Comment by sasaco** [comment]
<img width="1010" alt="スクリーンショット 2019-12-16 21 39 23" src="https://user-images.githubusercontent.com/4043298/70908078-b5a0b400-204d-11ea-95a1-4236ff0b7cf1.png">

**Comment by sasaco** [comment]
<img width="1027" alt="スクリーンショット 2019-12-16 21 48 54" src="https://user-images.githubusercontent.com/4043298/70908159-e2ed6200-204d-11ea-9a39-63cefc7a9372.png">

**Comment by sasaco** [comment]
<img width="1027" alt="スクリーンショット 2019-12-16 21 49 54" src="https://user-images.githubusercontent.com/4043298/70908264-1b8d3b80-204e-11ea-8a0c-d8bf9ee79225.png">

**Comment by sasaco** [comment]
<img width="980" alt="スクリーンショット 2020-01-26 16 05 39" src="https://user-images.githubusercontent.com/4043298/73131893-4fe51600-4056-11ea-8d7c-3e60728a5f19.png">

<img width="1420" alt="スクリーンショット 2020-01-26 16 11 29" src="https://user-images.githubusercontent.com/4043298/73131932-e7e2ff80-4056-11ea-8111-bd68a78ba7e1.png">

**Comment by sasaco** [comment]
![無題](https://user-images.githubusercontent.com/4043298/105258883-07f7c100-5bce-11eb-90e7-8d6c3a6dc432.png)

![image](https://user-images.githubusercontent.com/4043298/105258974-3d9caa00-5bce-11eb-9f75-5328acc2bcaa.png)


![image](https://user-images.githubusercontent.com/4043298/105259857-f6171d80-5bcf-11eb-86bc-22e32fa955a6.png)

**Comment by mizutani488** [comment]
![Uploading スクリーンショット 2021-02-16 113800.png…]()

**Comment by mizutani488** [comment]
![スクリーンショット 2021-02-16 113800](https://user-images.githubusercontent.com/69898951/108012127-f29a7900-704b-11eb-9e1a-43f56500bcfb.png)

**Comment by mizutani488** [comment]
![スクリーンショット 2021-02-16 115649](https://user-images.githubusercontent.com/69898951/108013013-1fe82680-704e-11eb-83c4-379b81e2edda.png)

**Comment by mizutani488** [comment]
![スクリーンショット 2021-02-16 120839](https://user-images.githubusercontent.com/69898951/108013786-bf59e900-704f-11eb-8eb8-d6be8b3dd63c.png)

**Comment by sasaco** [comment]
![image](https://user-images.githubusercontent.com/4043298/109371451-55abcb80-78e8-11eb-9b4e-c4cdcfdd83f6.png)




![image](https://user-images.githubusercontent.com/4043298/109371523-b935f900-78e8-11eb-9ef9-bbefcedfd034.png)





![FEM3D](https://user-images.githubusercontent.com/4043298/109371506-9c99c100-78e8-11eb-9a88-4cd25bb30df1.gif)

**Comment by sasaco** [comment]
![image](https://user-images.githubusercontent.com/4043298/109371557-d9fe4e80-78e8-11eb-832e-d420f5f86a0a.png)
