### ISSUE TITLE
Ctr+Xで荷重を切り取っても図が残る

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#218]
Ctr+Xで荷重を切り取っても図が残る

![resa](https://user-images.githubusercontent.com/4043298/155659901-9f941e59-81e4-461d-afd8-0d69b3098c83.gif)

**Comment by Masaki-beginner** [comment]
memberLoadDataが空データの時（load_value全削除の時）、以下のif文を通らないため発生。

if (this.currentIndex in memberLoadData)

このif文を通るとき、荷重が削除される。
