### ISSUE TITLE
断面力図 印刷時の max., min の表示がおかしい

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#219]
![image](https://user-images.githubusercontent.com/4043298/156864388-35fe112b-cef7-4de1-935a-27302bf2625e.png)

**Comment by sasaco** [comment]
sasazawa_#219

印刷時にいったん非表示にすることで間違いを避けた

**Comment by yuluji** [comment]
画像のようにチェックを付けて印刷すると、3D断面力図が印刷できる。


![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/13ed302a-182d-4f11-848b-cefbfba51120)

**Comment by yuluji** [comment]
断面力図をPDF印刷すると、左上に各ケースの最大値と最小値を表示するような機能があります。（現在はこの不具合のために非表示）

PDF印刷したときの最大値と最小値の数値が実際の最大値と最小値とは違う数値となってしまうため、この原因を調査し、修正してください。
