### ISSUE TITLE
PickUp 変位量 z軸回りの回転角が 印刷できない

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#229]
サンプルデータ

[frameWebForJS.zip](https://github.com/structuralengine/FrameWebforJS/files/8347072/frameWebForJS.zip)

![image](https://user-images.githubusercontent.com/4043298/160047633-5b5ddc71-ff6e-4d9f-93db-7ba70827f418.png)

**Comment by Masaki-beginner** [comment]
print.service.tsの500行目付近のforループの
Object.keys(json[type]) を this.ResultCombDisg.disgKeys3D に変更することで、対応可能。

print.service.tsの519行目付近の axis の中身が、2次元モードに対応していないことが原因
