### ISSUE TITLE
変位図を曲線にする

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#23]
このデータは、長さ3m の片持ち梁の先端に 300kN の荷重を載荷した計算で

先端の変形量
w = 0.00078m = 0.78mm
先端の回転角
θy = 0.00039rad = 0.02235 °

である

![IMG_20191221_161644 (1)](https://user-images.githubusercontent.com/4043298/71935182-86630a00-31e9-11ea-8fd1-f245a4038bbb.png)

エクセルファイルをここからダウンロードしてください
https://drive.google.com/file/d/1UCYxb6PMlbkjrcLqnMm7pRg3ZyILtITs/view?usp=sharing

**Comment by sasaco** [comment]
このエクセルと同じ図を描画してほしい

<img width="1411" alt="スクリーンショット 2020-01-08 7 48 12" src="https://user-images.githubusercontent.com/4043298/71935921-616f9680-31eb-11ea-9af7-b8450f8c689c.png">

**Comment by sasaco** [comment]
Excel マクロを見ると
```
Sub 変位表示(dv, tht, phi)

'補間点の節点変位の計算
 For i = 1 To idive + 1
  xi = (i - 1) / idive    '(x/l)
  uhe = (1 - xi) * de(1) + xi * de(7)
  vhe = (1 - 3 * xi ^ 2 + 2 * xi ^ 3) * de(2) + L * (xi - 2 * xi ^ 2 + xi ^ 3) * de(6) _
      + (3 * xi ^ 2 - 2 * xi ^ 3) * de(8) + L * (-xi ^ 2 + xi ^ 3) * de(12)
  whe = (1 - 3 * xi ^ 2 + 2 * xi ^ 3) * de(3) - L * (xi - 2 * xi ^ 2 + xi ^ 3) * de(5) _
      + (3 * xi ^ 2 - 2 * xi ^ 3) * de(9) - L * (-xi ^ 2 + xi ^ 3) * de(11)
'全体座標系への変換
  uhg = t(1, 1) * uhe + t(2, 1) * vhe + t(3, 1) * whe
  vhg = t(1, 2) * uhe + t(2, 2) * vhe + t(3, 2) * whe
  whg = t(1, 3) * uhe + t(2, 3) * vhe + t(3, 3) * whe
'補間点の変位を座標値に付加
  xd2 = (1 - xi) * xd(indv(ne, 1)) + xi * xd(indv(ne, 2)) + uhg * scv
  yd2 = (1 - xi) * yd(indv(ne, 1)) + xi * yd(indv(ne, 2)) + vhg * scv
  zd2 = (1 - xi) * zd(indv(ne, 1)) + xi * zd(indv(ne, 2)) + whg * scv

```

ここで、20分割した中間点の位置を計算し曲線を描いているようだ

**Comment by Masaki-beginner** [comment]
ソースコードの報告が完了していないので，1/8までの進捗報告を書いておきます．
Excelマクロの 「sub 変位表示()」全体のソースコードを確認して，VBAの記述方法を確認しました．　また関連する「sub 分割数()」のソースコードの確認や，nod，indv()などの変数の特定作業を行いました．
指示されたソースコードを理解する前段階で中断した状態です．

**Comment by sasaco** [comment]
src\app\components\three\geometry\ **three-displacement.service.ts**

### chengeData() 関数で変位の値を集計し, onResize() 関数で変位図を描画しています。

```javascript
  public chengeData(index: number): void {
    // 格点データを入手
/*・・・<省略>・・*/
    // 新しい入力を適用する
    for (const key of jsonKeys) {
/*・・・<省略>・・
 ↓ここで、変位の値を配列に追加(.push)している ① */
      this.targetData.push(
        {
          name: key,
          xi: i.x,
          yi: i.y,
          zi: i.z,
          xj: j.x,
          yj: j.y,
          zj: j.z,
          dxi: this.helper.toNumber(di.dx),
          dyi: this.helper.toNumber(di.dy),
          dzi: this.helper.toNumber(di.dz),
          dxj: this.helper.toNumber(dj.dx),
          dyj: this.helper.toNumber(dj.dy),
          dzj: this.helper.toNumber(dj.dz)
        }
      );
```

```javascript
  private onResize(): void {

    // 要素を排除する
    this.ClearData();

/*・・・<省略>・・
 ↓ここで、変位の値を節点座標に足している ② */

    for ( const target of this.targetData ) {

      let xi: number = target.xi;
      let yi: number = target.yi;
      let zi: number = target.zi;

      xi += target.dxi * this.scale;
      yi += target.dyi * this.scale;
      zi += target.dzi * this.scale;

      let xj: number = target.xj;
      let yj: number = target.yj;
      let zj: number = target.zj;

      xj += target.dxj * this.scale;
      yj += target.dyj * this.scale;
      zj += target.dzj * this.scale;

      const positions = [];
      positions.push( xi, yi, zi );
      positions.push( xj, yj, zj );
```

```javascript
/* ↓ここで、赤い線を描いている ③ */

      const threeColor = new THREE.Color(0xFF0000);
      const colors = [];
      colors.push( threeColor.r, threeColor.g, threeColor.b );
      colors.push( threeColor.r, threeColor.g, threeColor.b );

      const geometry: LineGeometry = new LineGeometry();
      geometry.setPositions( positions );
      geometry.setColors( colors );

      const matLine: LineMaterial = new LineMaterial( {
        color: 0xFF0000,
        linewidth: 0.001,
        vertexColors: THREE.VertexColors,
        dashed: false
      });
      const line: Line2 = new Line2( geometry, matLine );
      line.computeLineDistances();

      line.scale.set( 1, 1, 1 );
      line.name = target.name;

      this.lineList.push(line);

      this.scene.add( line );
    }
  }
```

修正はおそらく
①で 約20分割た点の情報を追加することで実現できると思います。

**Comment by Masaki-beginner** [comment]
指定されたソースコードの報告です．
'補間点の節点変位の計算’ では，分割数()で得られた idiv を用いて，(4.6)式の行列式の計算．
'全体座標系への変換' では，前段階で得たマトリックスt()を使用して，行列式の計算を行い，u, v, wを算出．
'補間点の変位を座標値に付加' では，座標系に変位を追加し，新たな座標値を算出．
と解釈しました．

これをもとに，ソースコードの修正を行います．

**Comment by Masaki-beginner** [comment]
#23遅くなっていてすいません．もうしばらくかかると思います．申し訳ありません．

質問なのですが，下の描画をするための入力値を教えてもらえませんか？
また，入力値の欄なのですが，格点～組み合わせ，までしか表示できていないのですが，
変位・支点反力・基本荷重断面力の3つの欄は，十分な数値を代入すると表示されるのでしょうか？
<img width="1411" alt="71935921-616f9680-31eb-11ea-9af7-b8450f8c689c" src="https://user-images.githubusercontent.com/59256812/72204398-cd3b5300-34ba-11ea-834e-8f9efe67a535.png">


また，変数について確認したいのですが，入力した点座標 i (xi, yi, zi), j (xj, yj, zj)における
変位量 dxi ～ dzj と解釈してるのですが，この認識で正しいでしょうか？

**Comment by sasaco** [comment]
@Masaki-beginner 
> 質問なのですが，下の描画をするための入力値を教えてもらえませんか？
また，入力値の欄なのですが，格点～組み合わせ，までしか表示できていないのですが，
変位・支点反力・基本荷重断面力の3つの欄は，十分な数値を代入すると表示されるのでしょうか？

→ 以下の手順で

1. [入力データファイル](https://drive.google.com/file/d/1v0rafFrgHoGwdK8SdmgjJIsxnNLWbYtJ/view?usp=sharing)を開く
1. ログインする (ID, パスワードに **test1105**)
1. メニュー：ファイル→計算 を実行する
で計算結果（変位、支点反力、断面力）ボタンが現れます

**Comment by sasaco** [comment]
> また，変数について確認したいのですが，入力した点座標 i (xi, yi, zi), j (xj, yj, zj)における
変位量 dxi ～ dzj と解釈してるのですが，この認識で正しいでしょうか？

→ はい、 下記の6つ の変数が、１本の線の両端の移動量です

- dxi, dyi, dzi 
- dxj, dyj, dzj 

これに、１本の線の両端の回転角

- rxi, ryi, rzi 
- rxj, ryj, rzj 

を追加してください

**Comment by sasaco** [comment]
検修終了しました

OKです。ありがとうございました
