### ISSUE TITLE
荷重の表示位置がおかしい

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#230]
ファイルを開くと正しい位置に表示されるが、

荷重の(新規)入力時に正しくない

![image](https://user-images.githubusercontent.com/4043298/160352408-38fe7806-2924-41b4-b6ed-3939d827f3fa.png)

**Comment by sasaco** [comment]
[frameWebForJS.zip](https://github.com/structuralengine/FrameWebforJS/files/8360763/frameWebForJS.zip)

**Comment by Masaki-beginner** [comment]
row1 -> row
