### ISSUE TITLE
断面力図（three-section-force.service.ts）をLine → path に変更

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#24]
### three-section-force.service.ts で線を描いている

![image](https://user-images.githubusercontent.com/4043298/72940707-a8948480-3db2-11ea-959e-60a2419f8100.png)

### これを下図のような面にしたい

<img width="736" alt="スクリーンショット 2020-01-23 7 35 34" src="https://user-images.githubusercontent.com/4043298/72940869-045f0d80-3db3-11ea-9243-06bf7dea5fa4.png">

**Comment by sasaco** [comment]
## ターゲットソースコードは以下の部分です。

**src/app/components/three/geometry/three-section-force.service.ts**

```typescript
  // 断面力の図を描く
  private addGeometory(key: string, axis: string, color: THREE.Color) {

    for (const target of this.targetData) {
      // 1つめのデータは部材情報
      const memberInfo: any = target[0];
      // ２つめのデータ以降が断面力情報
      const positions = [];
      const colors = [];
      for (let i = 1; i < target.length; i++) {
        const force: any = target[i];
        let x: number = force.worldPosition.x;
        let y: number = force.worldPosition.y;
        let z: number = force.worldPosition.z;
        x -= force[key] * memberInfo[axis].x * this.scale;
        y -= force[key] * memberInfo[axis].y * this.scale;
        z -= force[key] * memberInfo[axis].z * this.scale;
        positions.push(x, y, z);
        colors.push(color.r, color.g, color.b);
      }

      const geometry: LineGeometry = new LineGeometry();
      geometry.setPositions(positions);
      geometry.setColors(colors);

      const matLine: LineMaterial = new LineMaterial({
        color: 0xFF0000,
        linewidth: 0.001,
        vertexColors: THREE.VertexColors,
        dashed: false
      });
      const line: Line2 = new Line2(geometry, matLine);
      line.computeLineDistances();

      line.scale.set(1, 1, 1);
      // line.name = '';
      this.lineList.push(line);
      this.scene.add(line);
    }
  }
```

**Comment by sasaco** [comment]
### コミット[断面力図を追加]を取得して作業してください

<img width="938" alt="スクリーンショット 2020-01-23 7 39 26" src="https://user-images.githubusercontent.com/4043298/72941121-89e2bd80-3db3-11ea-8994-df0991fb2d94.png">

**Comment by sasaco** [comment]
サンプルデータはここからダウンロードしてください
https://drive.google.com/open?id=12rUZTA43DL-Jvpi-DZkF0PC3AGccAJ7J

**Comment by Masaki-beginner** [comment]
断面力値の表示，追加しました．
ターゲットソース外で，バグが発生し，対処法が分かりませんでした．
ターゲットソース内でも，requireの部分で，errorが出てしまいました．
バグは残っていますが，出力はできている状態です．

追加したソースがmeshデータを作成するものにしたので，linelistに追加できず，
ClearData()で削除できなく，パラメータ変更時に，以前のmeshデータが残る状態です．

大変遅くなってしまい，申し訳ありませんでした．

**Comment by sasaco** [comment]
修正した
