### ISSUE TITLE
パネルが四角に表示できない

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#250]
サンプルデータ
[frameWebForJS (1).zip](https://github.com/structuralengine/FrameWebforJS/files/9388446/frameWebForJS.1.zip)

![image](https://user-images.githubusercontent.com/4043298/185775909-924cb363-c641-4eba-aca1-2c9b5db929d8.png)

**Comment by yuluji** [comment]
解決したが、新たな問題が発生…
https://github.com/structuralengine/FrameWebforJS/issues/262
