### ISSUE TITLE
部材荷重の 部材1, 部材2 を入力するとエラー

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#256]

**Comment by sasaco** [comment]
@shibasaki48 
エラー発生個所の特定をお願いします。詳しい事象は後程説明します

**Comment by sasaco** [comment]
[立体骨組構造解析ソフトver1 (2) (8).zip](https://github.com/structuralengine/FrameWebforJS/files/6186808/ver1.2.8.zip)

**Comment by sasaco** [comment]
ERROR TypeError: Cannot read property 'm1' of undefined
部材２より部材１の絶対値が大きいとerror発生。
原因：input-load-service.tsの612行目以降の場合分けが不十分。616行目のtargetLoadがundefinedになっている。

**Comment by shibasaki48** [comment]
ERROR TypeError: Cannot read property 'toString' of undefined
部材1、２ともにプラスのとき、部材1より部材2の方が値が大きいとerror発生。
原因：input-load.service.tsの634行目のtargetLoad.L1がundefinedになっている。

**Comment by shibasaki48** [comment]
errorとして表示はされないが、
部材1，2がどちらもプラスのとき、部材1の方が大きいと部材2は入力していないものと同等に扱われている。

**Comment by sasaco** [comment]
関連
#258 
https://github.com/structuralengine/FrameWebforJS/issues/258

**Comment by shibasaki48** [comment]
部材1より部材2の方が値が大きい場合

部材1と部材２を入れ替える

4　-1
↓ 内部で変換する
1  -4

**Comment by shibasaki48** [comment]
> ERROR TypeError: Cannot read property 'm1' of undefined
> 部材２より部材１の絶対値が大きいとerror発生。
> 原因：input-load-service.tsの612行目以降の場合分けが不十分。616行目のtargetLoadがundefinedになっている。

解決
