### ISSUE TITLE
荷重名称と荷重強度のリンク

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#257]
荷重名称を削除した時に、荷重強度の内容が残ってしまっている。

荷重名称を消した時に、荷重強度も一緒に消えるように設定して欲しいです。

![1](https://user-images.githubusercontent.com/4043298/111944325-ba8ac800-8b1a-11eb-92b3-04433c466d46.png)

**Comment by shibasaki48** [comment]
初めから名称が書かれていないパターン（24)sumple_Data_No6.3 (1).jsonのデータ）
