### ISSUE TITLE
節点荷重と要素荷重の非表示ボタンがほしい

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#259]
入力画面を補足して Three.js の範囲を増やす狙い

![image](https://user-images.githubusercontent.com/4043298/189023744-fdd7eeb1-92b7-4d59-9eb1-f82192163148.png)

**Comment by yuluji** [comment]
下記のように修正する。
①デフォルトでは要素荷重が展開され、節点荷重が閉じた状態にする。
②節点荷重をクリックすると要素荷重が閉じ、節点荷重が開かれた状態となる。
③どちらかに数値が入力されている場合は、その荷重入力欄を展開し、もう片方の荷重入力欄を閉じる。
④片方に数値が入力されている状態で、もう片方に数値が入力された場合はエラーメッセージを表示する。

[修正内容.pdf](https://github.com/structuralengine/FrameWebforJS/files/10312412/default.pdf)
