### ISSUE TITLE
分布荷重の各点に生じる荷重の重複による荷重図反映問題について

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#261]
等分布荷重を入力した際に、各点で重複が生じるため図形が以下の画像のように飛び出てしまうという問題点が生じた。
![image](https://user-images.githubusercontent.com/4043298/111950094-296d1e80-8b25-11eb-8d99-ae081c6f32ec.png)

**Comment by Masaki-beginner** [comment]
L2の値が負の値になっているということは，部材の外側に荷重がかかっているということですよね．
その点が問題なのであれば，L1及びL2の値が負であるときの仕様を追加することになるのでしょうか．
当たり判定の部分の修正だと思うのですが，一応確認させていただきました．

**Comment by sasaco** [comment]
サンプルデータ

[立体骨組構造解析ソフトver1 (2) (8).zip](https://github.com/structuralengine/FrameWebforJS/files/6208576/ver1.2.8.zip)

**Comment by Masaki-beginner** [comment]
![スクリーンショット 2021-03-26 113446](https://user-images.githubusercontent.com/59256812/112569353-5f611a00-8e27-11eb-96e5-89ff9961fa7f.jpg)
three-load.service.tsのtargetloadの段階で，L1=0.000, L2=-0.974の荷重（入力値）が，部材番号7の荷重(id=0)と，部材番号8(id=1)の荷重に分解されている．
input-load.service.tsの592行目付近（他，612, 649）に以下のコメントアウトがあり，
`// 要素番号 m2 にマイナスが付いた場合の入力を分ける ------------------------`
ここの処理で，複数の荷重に分割されていると思われる．
