### ISSUE TITLE
数字の入力が連続して発生する

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#270]
箇所・項目を問わず、テンキーを使用して数字を入力する際に一文字のみ入力したはずが連続して同じ数字が入力されるという事態がランダムに発生する。発生時には別のタブを使用または使用中のウィンドウを閉じて新しいウィンドウにてファイルを開きなおした場合も同じ事象が続けて起こることを確認。

**Comment by yuluji** [comment]
test
https://www.notion.so/GitHub-Notion-1173e4dfd8444909bc0414c144c45c2c

**Comment by yuluji** [comment]
test2
https://www.notion.so/66b880959bcb476ea7c615062d3c3228?v=5013fd0353714134a39df85d1af05839

**Comment by yuluji** [comment]
https://www.notion.so/1-368ee2fc86544c36af2111d4849762e7

**Comment by sasaco** [comment]
#280 
で原因を特定、再度この問題にチャレンジしている
