### ISSUE TITLE
分布荷重の重なりをずらす際に

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#271]
下図において

荷重2 は 荷重1 と重ならないため
初期位置に描画したい

![image](https://user-images.githubusercontent.com/4043298/112561019-af37e500-8e17-11eb-818e-6c0e3b495ef8.png)

荷重3 は 荷重2 と重なるため
ずらした位置でよい

**Comment by Masaki-beginner** [comment]
2021/3/27 15:07のコミットで接触判定を追加
ただし，分布荷重(y, z)のみに追加してある．

今後，他の荷重図でも使用する場合には，使用を追加する必要がある．
