### ISSUE TITLE
フォーカスが無い状態で[Enter]を押したら次のセルに移動したい

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#281]
### 右に移動するのか、下に移動するのか 各画面ごとに選択したい

![Animation3](https://user-images.githubusercontent.com/4043298/209048230-626da7f8-67b1-4be1-bb63-41132aeb1b69.gif)

**Comment by yuluji** [comment]
入力後、「Enter」で移動させる方向は基本右でOK
ただし、一番右のセルで「Enter」が押されたら、一行下の一番左のセルに移動するようにしたい。
※おそらく現状でもこのようにはなっている。

**Comment by yuluji** [comment]
サンプルファイル（02_FrameWeb.json）
[02_FrameWeb.zip](https://github.com/structuralengine/FrameWebforJS/files/10311446/02_FrameWeb.zip)

セットアップに必要なフォルダ（enviroments.zip）
※添付画像の位置にenviromentフォルダを移動すればOKです。
![image (1)](https://user-images.githubusercontent.com/109077766/209742892-4628a695-89c8-4215-a08f-1c0080650720.png)
