### ISSUE TITLE
荷重強度の荷重名称のマージンを他の要素と揃える

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#282]
### 荷重名称が長いときに下図の位置になるのだが
マージンを他の要素と揃える

![image](https://user-images.githubusercontent.com/4043298/209051008-df181a93-5f0d-41f0-beeb-2277265e506e.png)

### 荷重名称が短いときはこれでよい
![image](https://user-images.githubusercontent.com/4043298/209051232-a56f7d63-cc6f-441f-8a12-76e58d826eed.png)

**Comment by yuluji** [comment]
デスクトップ版固有の問題の可能性あり

**Comment by sasaco** [comment]
デザイナーさんによる全体的な改定予定があるのでクローズします
