### ISSUE TITLE
ファイルを開い時に前のデータのresult をクリアしてない

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#283]
## ファイルを開い時に　変位・反力・断面力のボタン　は非表示になるハズ

前のデータのresult をクリアしてないため 変位・反力・断面力のボタンが残っている

Electron アプリで不具合を確認したので、Webアプリでも同様の不具合があるか確認されたし

![Animation4](https://user-images.githubusercontent.com/4043298/209051865-5f0985a8-bbb6-49c6-8530-89cb1f059214.gif)

**Comment by yuluji** [comment]
webアプリでは発生しない。
