### ISSUE TITLE
nodeNo, memberNoを表示すると 入力グリッドの上(z-index)に表示される

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#294]
サンプルデータ
[frameWebForJS.zip](https://github.com/structuralengine/WebDanforJS/files/10398836/frameWebForJS.zip)

![Animation3](https://user-images.githubusercontent.com/4043298/211995059-eb3ac64a-8246-48eb-b5c6-3d45497eb079.gif)

**Comment by yuluji** [comment]
デザイン更新に伴い修正完了
