### ISSUE TITLE
断面力 印刷の際の部材選択テーブルがなくなっている

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#296]
#276 印刷画面のコンソールを整理 
の変更により

### 断面力、COMBINE断面力、PICKUP断面力 印刷時は下図のようになっている

![image](https://user-images.githubusercontent.com/4043298/212610006-b0883a2e-1c37-4a34-9017-c7aea498c1b9.png)

### 部材選択 テーブルがなくなってしまった

![image](https://user-images.githubusercontent.com/4043298/212610148-50c5592d-5946-4b3b-b99b-82fee7c4a436.png)

## 復活してください

**Comment by yuluji** [comment]
修正済み
