### ISSUE TITLE
プレート 機能の追加

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#31]
![new-plate-solver-mesher](https://user-images.githubusercontent.com/4043298/92181612-99b39b80-ee84-11ea-87ff-97e46f85d7a6.gif)

**Comment by sasaco** [comment]
![image](https://user-images.githubusercontent.com/4043298/92184864-35490a00-ee8d-11ea-9073-b39cfe1665f7.png)

**Comment by Masaki-beginner** [comment]
＜仕様の確認＞
input項目は「No. (固定値)」「nodeのポイント (無限個・着目点と同様な仕様)」「材料No」
パネル部分は。three.jsのshapeを使って描画

**Comment by Masaki-beginner** [comment]
panelの仕様を追加
サンプルデータを以下に添付

**Comment by sasaco** [comment]
一応計算できるようにはした


が、自動分割など
