### ISSUE TITLE
計算開始ボタン押下時にクルクルを表示するタイミング

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#311]
計算開始ボタン押下時にクルクルを表示するタイミングを

計算開始ボタン押下直後にする

今は、データの集計が終わったタイミングでクルクルを表示しているので、
大きいデータの場合はビジー状態になる
![Animation](https://user-images.githubusercontent.com/4043298/216269851-dbe3a898-b511-49b9-a844-be76f9c4767b.gif)

大きいデータ
[frameWebForJS.zip](https://github.com/structuralengine/FrameWebforJS/files/10566762/frameWebForJS.zip)

**Comment by yuluji** [comment]
【現在のプロセス】
計算ボタンを押下
↓
「計算を開始します」の表示
↓
ロード表示（クルクル）
↓
計算完了

【修正後のプロセス】
計算ボタンを押下
↓
ロード表示（クルクル）
↓
「計算を開始します」の表示
↓
ロード表示（クルクル）
↓
計算完了
