### ISSUE TITLE
車両横荷重の荷重がずれている。

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#315]
車両横荷重の荷重図がずれて表示される。
![4](https://user-images.githubusercontent.com/4043298/113960834-07cba100-9860-11eb-90a1-84230540b725.png)

**Comment by sasaco** [comment]
[CaseTEST_荷重ずれ.zip](https://github.com/structuralengine/FrameWebforJS/files/6275725/CaseTEST_.zip)

**Comment by Masaki-beginner** [comment]
![image](https://user-images.githubusercontent.com/59256812/114300383-05d13e80-9afb-11eb-91a5-a1c8d116f879.png)
14~17にかけて挙動の確認をしてみましたが，上のような挙動は確認できませんでした．
上のような挙動が起こったときの他の条件はありますか？
