### ISSUE TITLE
解析結果の印刷機能をチェックする

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#320]
このデータで解析した後
pickup 断面力を印刷するときに不具合が出ないか

https://t.co/QFx6S5D6zL?amp=1

**Comment by mizutani488** [comment]
![image](https://user-images.githubusercontent.com/69898951/115098985-20c60780-9f6e-11eb-8712-1d592979a3cf.png)

5行目までしか記載していないのに26行目までデータが入っており、27-52までは空っぽのデータとして認識されている。
case27以降空っぽとなるためにデータ欠損で印刷に不備が出ているものと考えられる。

**Comment by sasaco** [comment]
修正しました
