### ISSUE TITLE
「ファイルを保存」した時の拡張子がおかしい

### ISSUE THREAD

**Issue by Masaki-beginner** [structuralengine/FrameWebforJS#335]
「ファイルを保存」した際の拡張子がjsonとは子よなる場合がある。
2D時に「ファイルを保存」をした時、13ファイルが生成される。
defaultのファイル名の「立体骨組構造解析ソフトver1.3.1」では1ファイルが生成される。

**Comment by sasaco** [comment]
ver1.3.2 で、修正しました
