### ISSUE TITLE
ピックアップ断面力を印刷する部材を選択できるようにしてほしい

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#34]

**Comment by sasaco** [comment]
![image](https://user-images.githubusercontent.com/4043298/138012512-fea24e6b-7209-484d-a311-d692c63fb01e.png)

**Comment by mizutani488** [comment]
水谷メモ
結果右側に選択画面を制作する．
その際にセレクトボックスを作って切り替えられるようにする

**Comment by mizutani488** [comment]
完了しました
