### ISSUE TITLE
(NEW)デザインリニューアル

### ISSUE THREAD

**Issue by arch-mania** [structuralengine/FrameWebforJS#350]
## 概要
Figmaをもとにデザインを作成する。
https://www.figma.com/file/AaRuiQIDW3txzDp2K92Wcg/NEW!-STRUCTURAL-ENGINE?node-id=0-1&t=r139JrXBUeNXE08Z-0

## 実装内容
・デザイン変更
・使用ポイントを追加(DB取得などは対象外)
・コントロールをケースヘッダーに統合
・ケースをモーダル外のケースヘッダーに統合
・ドッキングモーダルに変更

**Comment by sasaco** [comment]
フローティングウインドウの外側のスクロールバーを消してほしい
ただし、（画面幅が小さい時の）横スクロールバーは必要
![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/45fc5f9e-d5e2-4253-be94-c545f4d11ea8)

**Comment by sasaco** [comment]
文字の両端に余白を付けてほしい
![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/dacd55a7-dd12-434e-887c-8e534e7f751a)

**Comment by sasaco** [comment]
荷重強度表示中のリストは 荷重名称を表示
![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/8faa906a-05d8-45ec-8ce9-78e507f0e249)

変位や、支点反力と同じです
![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/56b348dd-17f9-49ee-b37f-85b4b5727566)

**Comment by sasaco** [comment]
![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/5f58c63b-9e2a-424d-a374-9e445fa56746)

**Comment by sasaco** [comment]
英語表記とカタカナ表記
- Combine と コンバイン
- 

![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/d2386146-a273-436a-a811-b8f101dc3a77)

**Comment by sasaco** [comment]
印刷中にクルクルを付けてほしい
![Animation2](https://github.com/structuralengine/FrameWebforJS/assets/4043298/211c9c08-3730-4869-9352-277e55bbaa7d)

**Comment by yuluji** [comment]
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/d7cf5038-2a21-4e64-90ce-c43928e78e08)
チャットボットのデザイン実装抜け？

**Comment by yuluji** [comment]
[recording-2023-05-25-15-59-35.webm](https://github.com/structuralengine/FrameWebforJS/assets/109077766/f72de203-96bd-4558-8b21-1a8e357eec31)
支点反力で荷重の変更がは反映されない。

**Comment by yuluji** [comment]
↑の補足です。
「支点反力」の表について、
「基本ケース」「コンバイン」「ピックアップ」などの変更は反映されるが、
「1.固定死荷重」「2.付加死荷重」などのページ変更が反映されず、常に同じ値が表示されてしまう。
![recording-2023-05-29-17-30-30](https://github.com/structuralengine/FrameWebforJS/assets/109077766/74e9e8d1-ec83-40dc-a18b-82ed5b853cf6)
