### ISSUE TITLE
断面力の出力が足りない

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#354]
下記のサンプルデータ
[解析結果.zip](https://github.com/structuralengine/FrameWebforJS/files/11580630/default.zip)

において部材番号5以降の結果が出てない

![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/ad994b90-5a42-4a76-82d7-f26bd0066e36)

**Comment by sasaco** [comment]
データは取得できており動画の 00:15 のように再描画すると表示される

https://github.com/structuralengine/FrameWebforJS/assets/4043298/a1213b94-6266-4afe-9d26-4a791f927487

src\app\components\result\result-fsec\**result-fsec.component.html** でテーブルを生成しているが

[itemSize](https://material.angular.io/cdk/scrolling/overview) が 関係してそう

![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/ba04257d-189b-4e81-bb39-fee6220183a7)

**Comment by yuluji** [comment]
「変位」「支点反力」「部材断面力」の出力メニューにおいて、
部材番号5以降の結果が表示されない。

![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/c2a3e037-b596-4008-a4ab-6909e85f6564)

**Comment by yuluji** [comment]
FrameWebForJS の データグリッドについて
入力画面 -> paramQuaryGrid
計算結果画面 -> htmlの標準 table
となっているため、計算結果画で下記の不具合が生じています.

計算結果画面もparamQuaryGridを使用してください。

**Comment by namnguyen0705** [comment]
@yuluji Can you be more clear, please?

**Comment by sasaco** [comment]
@namnguyen0705 

src\app\components\ **result** にある .component.html の **<table>** を 

src\app\components\ **input** で使われている 

**<app-sheet** に変えてください

![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/da5ce112-e302-4fbd-ae2c-b9b6cad01411)

**Comment by namnguyen0705** [comment]
@sasaco do you want me to convert it to app-sheet?

**Comment by sasaco** [comment]
yes、htmlの標準table から app-sheet(=paramQuaryGrid) に変えてください
