### ISSUE TITLE
３Dの場合 反力図印刷機能がほしい

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#364]
反力図印刷機能はデザイン変更前は画面印刷できた

![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/71c90f89-c773-4bcc-abd7-01cd80823a05)

**Comment by yuluji** [comment]
@sasaco 
「画面印刷」に「反力図」「コンバイン反力図」「ピックアップ反力図」の項目を追加し、支点反力のケースごとに画面印刷を行うであってますか？

**Comment by sasaco** [comment]
> 「画面印刷」に「反力図」「コンバイン反力図」「ピックアップ反力図」の項目を追加
> 支点反力のケースごとに画面印刷を行う

-> はい、その通りです。あってます。仕組みは、断面力図と同じです

**Comment by yuluji** [comment]
「反力図」の印刷に関しては下記を参照してください。
src\app\components\print

**Comment by yuluji** [comment]
現在の印刷ウィンドウでは「画面印刷」の中に「反力図」がありませんが、印刷機能自体は作成済みなので、「反力図」「コンバイン反力図」「ピックアップ反力図」が印刷できるように、印刷ウィンドウ内に項目を追加してください。
印刷対象などに関しては「断面力図」「コンバイン断面力図」「ピックアップ断面力図」と同様の設定にしてください。

![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/4172a2e1-ce2f-4543-89cf-90d88c51e5f6)

**Comment by namnguyen0705** [comment]
Please provide for me Name of Menu English and Japanese

**Comment by yuluji** [comment]
@namnguyen0705 
Please do this.
「Japanese」
・反力図
・コンバイン反力図
・ピックアップ反力図

「English」
・Reaction diagram
・Combine reaction diagram
・Pickup reaction diagram

**Comment by namnguyen0705** [comment]
so, I will add new three that menus to the prints dialog and they are the same as "Combine force diagram" 
![image](https://github.com/structuralengine/FrameWebforJS/assets/103914919/4ab6afb4-5bd1-4442-8a8d-ab9785bee1c2)

**Comment by yuluji** [comment]
@namnguyen0705 
Reaction diagram" should be the same as "Displacement diagram" with no option for print target. 
Combine reaction diagram" and "Pickup reaction diagram" are the same as "Combine force diagram".

**Comment by namnguyen0705** [comment]
do you have the code for the print Reaction?

**Comment by yuluji** [comment]
Can you create it in JS using the "Section force" printing method as a reference?
