### ISSUE TITLE
変位図印刷のときは印刷対象選択は不要

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#367]
![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/db481ee9-b49a-4aa5-8e3e-d186de22b172)

**Comment by yuluji** [comment]
変位図は「基本ケース」の印刷しか行わないため、
画面印刷＞変位図にある選択肢を削除

![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/c3e966a2-ecbc-4cd3-82d1-6b1b30a80944)

**Comment by namnguyen0705** [comment]
@yuluji Can you be more clear, please?

**Comment by sasaco** [comment]
@namnguyen0705 
Displaement の印刷時は、 SElect print target を非表示にしてください
