### ISSUE TITLE
ローディングがうまく表示されない。

### ISSUE THREAD

**Issue by yuluji** [structuralengine/FrameWebforJS#375]
https://github.com/structuralengine/FrameWebforJS/assets/109077766/bdd08645-b1ee-40d0-ac2e-22b72e36abe8

**Comment by yuluji** [comment]
ファイルを開くときと、計算を実行するときに表示されるローディングのモーションが正常に動作していない。
正常に動作している場合、時計回りに回転する。

**Comment by yuluji** [comment]
The loading motion displayed when opening a file and when performing a calculation is not working properly.
If it is working correctly, it rotates clockwise

**Comment by namnguyen0705** [comment]
https://github.com/structuralengine/FrameWebforJS/assets/103914919/c5538fea-7fa8-4637-b3ad-b7b31ea710ea
Loading is using CSS Stylesheet code, I can't reproduce according to your video.
Do you want me to replace it with another CSS animation code?
@yuluji

**Comment by yuluji** [comment]
@namnguyen0705 
報告ありがとうございます。
自分も確認しました。
確かに、ローカル環境だと正常に動作しているようです。
私の方で原因を調査します。
他のタスクへ回っていただいてもいいですか？

**Comment by namnguyen0705** [comment]
Ok, I will check other task in Notion
