### ISSUE TITLE
水平スクロールバーが出ない

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#378]
![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/fee34d2f-ae57-454c-be9b-a3588939d107)

**Comment by yuluji** [comment]
入出力のウィンドウは、右または下に固定されている状態と、フローティングウィンドウになっている状態の2つの状態がある。

固定されている場合、
入力ウィンドウでは鉛直方向のスクロールバーが2つ表示され、水平方向のスクロールバーは表示されない。
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/5a815dec-a287-4a54-a44e-8a9b24c2a447)

出力ウィンドウでは鉛直方向のスクロールバーが1つ表示され、水平方向のスクロールバーは表示されない。
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/7049e265-a7dd-4614-8dfa-b882b0901cf2)

固定されていない場合（フローティングウィンドウの場合）
入力ウィンドウでは鉛直方向のスクロールバーが2つ表示され、水平方向のスクロールバーが1つ表示される。
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/80e755ca-3b87-4a15-8566-dacdd4e43e3d)

出力ウィンドウでは鉛直方向のスクロールバーが1つ表示され、水平方向のスクロールバーが1つ表示される。
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/e489cdd6-803e-4f1e-a120-eb411caebbad)

**Comment by yuluji** [comment]
それぞれ、スクロールバーの表示形態が異なるため、
すべての状態で「鉛直方向のスクロールバーが1つ表示され、水平方向のスクロールバーが1つ表示される。」となるように修正をお願いします。
