### ISSUE TITLE
「組み合わせ」の入力に不備があってもピックアップ断面力を計算できるように修正

### ISSUE THREAD

**Issue by yuluji** [structuralengine/FrameWebforJS#388]
[sample01.zip](https://github.com/structuralengine/FrameWebforJS/files/11862577/sample01.zip)

例えばこのサンプルデータのように、ピックアップでコンバインの91～94を指定しているが、
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/51e09dc3-f826-4801-ae23-980b81b37f20)

コンバインでは57までしか数値を設定していないときも、57までのコンバインを用いたピックアップの計算は実行するように修正
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/9aa789c3-dc69-4c44-9f09-7c4c9a35d381)

**Comment by yuluji** [comment]
「荷重」と「組み合わせ」の関係については下記を参照
[Combine relationship.pdf](https://github.com/structuralengine/FrameWebforJS/files/11862636/Combine.relationship.pdf)

**Comment by sasaco** [comment]
この方法だと、いったん計算しないと pikup入力画面 が開けなくなる

サンプルデータ（計算してないデータ）
[CDT__BLP3_1_.zip](https://github.com/structuralengine/FrameWebforJS/files/12331474/CDT__BLP3_1_.zip)

![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/0bcd3eeb-5e95-48c4-9c21-d74e31716da9)


this.result['combList'];　は計算しないと null なのでNG

**Comment by sasaco** [comment]
このissue [#388](https://github.com/structuralengine/FrameWebforJS/issues/388)はそもそも 入力画面に関するものではなく
計算実行 に関する issue である

計算結果：部材断面力->ピックアップは表示されないです

![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/c25fe596-6c0a-49a1-adde-4c3a29036625)

**Comment by yuluji** [comment]
@huynd2904 

The ticket was completed a while ago, but I found a bug that I would like you to address.
We have reviewed this from the requirements and would appreciate your response as follows.

(1) Revision Policy
We would like to do the deed at the time of calculation, instead of limiting or processing in the input field.
Currently, though, only the values set in the combine can be entered in the pickup,
Please modify the policy so that any value can be entered in the combine and pickup, and if a value not set in the combine is used in the pickup at the time of calculation, the calculation for that line should not be performed.

(2) Areas to be modified
I think this problem is caused by a bug in worker1 and worker2 from the set◯PickupJson() function in result-pickup-◯◯.setvice.ts.
Since worker1 and worker2 are background processes, they do not respond to breakpoints and are difficult to debug.
Therefore, develop a debugging function worker1_test that has the same code as worker1.
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/79b0ad22-56a0-496e-a699-e793d8d292a3)

**Comment by huynd2904** [comment]
Oki , I'll check it again.

**Comment by huynd2904** [comment]
Hi @yuluji 
I have checked and get some errors when calculate. That is check null or undefined conditional in worker1 and worker2.
Can I push code and you check it for me? 
Same as image. I checked null or undefined
![image](https://github.com/structuralengine/FrameWebforJS/assets/132535412/d75b26bc-c7ea-4d33-8740-2c923d7d4d47)

**Comment by yuluji** [comment]
@huynd2904 

I saw it.
I think the additional changes are very good.
However, when I open a file that specifies a number in the pickup that is not set in the combine, the number that is not set in the combine seems to disappear from the pickup.

For example, as shown in the image, in the wdj file, 94 is entered in pickup, but when the file is opened, the numbers after 57 are not displayed.
Could you please fix this problem if possible?
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/5cbd97da-b70e-4ac0-97c5-2d3bf10e5c02)

![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/730ede11-091d-458b-90a9-0d8c254b53c0)

**Comment by yuluji** [comment]
I tried with this attachment.

https://github.com/structuralengine/FrameWebforJS/issues/388#issue-1773733571

**Comment by huynd2904** [comment]
OK, I have pushed, you can check it. Because first check tichket , I had checked value not set from the pickup in the combine
![image](https://github.com/structuralengine/FrameWebforJS/assets/132535412/5066987a-3d07-4311-982a-86691c26788a)
