### ISSUE TITLE
印刷の軸線スケールの入力数値が表示されない（空白になる

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#400]
サンプルデータ
[P40P42_.zip](https://github.com/structuralengine/FrameWebforJS/files/12101498/P40P42_.zip)

![develkop](https://github.com/structuralengine/FrameWebforJS/assets/4043298/19f91dcd-f70d-46b7-ad03-e274ba2f40c7)

**Comment by yuluji** [comment]
印刷ウインドウから「軸線スケール」では「Auto」モードと、「数値」モードの2つがあります。
「軸線スケール」の項目に数値を入力すると、「数値」モードとなり、任意の縮尺で図を印刷することができます。
しかし、動画のように、「軸線スケール」に数値を入力すると数値が表示されなくなってしまっているようです。
入力した数値を改行している。もしくは白文字で表示してしまっていることが原因と考えられます。

原因を調査し、数値を入力した場合は、入力した数値を表示するように修正してください。
また、入力した数値を削除した場合は、「Auto」に切り替わるようにしてください。
