### ISSUE TITLE
印刷項目が不正の場合、警告メッセージの後に閉じないようにする

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#401]
サンプルデータ
[P40P42_.zip](https://github.com/structuralengine/FrameWebforJS/files/12101505/P40P42_.zip)

印刷項目が不正の場合、警告メッセージの後に印刷画面が閉じてしまう。
再入力のチャンスを

### 断面力図 の印刷で 印刷対象を何も選択しなかった場合の例
![develkop](https://github.com/structuralengine/FrameWebforJS/assets/4043298/58aeaf44-fa40-4dd1-84cf-8982f7823e68)

**Comment by yuluji** [comment]
【2Dモードの場合】
「Sectional force diagram」「combine force diagram」「Pickup force diagram」の印刷において、「Select print target」の項目を一つも選択せずに印刷を開始すると、「please select target」と警告文が出ます。
ここで「Close」を押すとデフォルト画面に戻ってしまいますが、直前まで開いていた印刷ウィンドウへ戻るように変更してほしいです。
（仮に、「combine force diagram」を開いていた場合は、「Close」を押した後に「combine force diagram」の印刷ウィンドウへ戻るようにしてください。）
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/cce4723a-9fd9-4fbb-bc15-1e3dca78f51c)
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/4c261180-e455-4e74-aff4-c3af9648a76d)


【3Dモードの場合】
「Sectional force diagram」「combine force diagram」「Pickup force diagram」の印刷において、「Select print target」の項目を一つも選択せずに印刷を開始すると、警告文が出ずにデフォルト画面へ戻ってしまします。
「Select print target」の項目を一つも選択せずに印刷を開始したときに2Dモードの時と同じ警告文を表示し、
警告文の「Close」を押すと直前まで開いていた印刷ウィンドウへ戻るようにしてほしいです。
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/c48b6ab2-9eea-4bae-852b-fc0f7fecde5a)
