### ISSUE TITLE
変位図の印刷が終わるとウィンドウ閉じるボタンが表示されなくなる

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#405]
![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/048197f3-1f7e-4444-af71-a71857478ec6)

サンプルデータ

[frameWebForJS.zip](https://github.com/structuralengine/FrameWebforJS/files/12235077/frameWebForJS.zip)

変位図の印刷が終わるとウィンドウ閉じるボタンが表示されなくなる

https://github.com/structuralengine/FrameWebforJS/assets/4043298/e06484ea-3f01-4d7c-af9f-e80226800308

**Comment by yuluji** [comment]
3Dモードで「Print screen」内の項目を印刷すると、
入出力ウィンドウのタブが非表示になってしまうようです。
修正をお願いします。
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/ac69bacc-99d7-4003-b330-2b1eef535710)
