### ISSUE TITLE
断面力図 印刷時の縮尺の数値が見えない

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#406]
![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/a1db7b2f-b509-493c-bbc4-50b12fa27531)

”自動”の文字は見えるが、数値を入力すると見えなくなる。改行しているのではないか？

サンプルデータ

[sample.zip](https://github.com/structuralengine/FrameWebforJS/files/12235151/sample.zip)

**Comment by yuluji** [comment]
Web版（masterブランチ）とdevelopブランチを確認しましたが、
自分の環境では状況を再現できないです。

**Comment by sasaco** [comment]
これと同じ問題でした。
https://github.com/structuralengine/FrameWebforJS/issues/400

こっちはクローズします
