### ISSUE TITLE
右クリックして コピペメニューを表示

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#415]
![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/6049bc2d-abd0-4b00-8590-cf4e25facf48)

**Comment by yuluji** [comment]
現在、下記項目のように「Ctrl + C」や「Ctrl + V」でセルのコピーとペーストなどを行うことができます。
・「Ctrl + C」：コピー
・「Ctrl + V」：ペースト
・「Ctrl + X」：切り取り
・「Ctrl + Z」：元に戻す

右クリックメニューを追加してください。項目は以下の通りでお願いします。
【英語の場合】
・clipping　Ctrl+X
・copy　Ctrl+C
・paste　Ctrl+V
・undo　Ctrl+Z
【日本語の場合】
・切り取り　Ctrl+X
・コピー　Ctrl+C
・貼り付け　Ctrl+V
・元に戻す　Ctrl+Z
