### ISSUE TITLE
荷重名称、荷重強度 は並列表示

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#430]
# 荷重
![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/3937e9c9-04eb-4e7c-aad0-6cdbebba456a)

**Comment by sasaco** [comment]
# 変位
![image](https://github.com/structuralengine/FrameWebforJS/assets/4043298/be6cf7df-1824-44b5-aabd-7a0930016483)

**Comment by Yuzuru-Kimura** [comment]
Please modify to display "Name of Load" and "Load Strength" in parallel.
See attached document for details.

![image](https://github.com/structuralengine/FrameWebforJS/assets/147780035/f238e313-4835-4a9a-b577-e0c6b2102094)

[issue430.xlsx](https://github.com/structuralengine/FrameWebforJS/files/13521442/issue430.xlsx)
