### ISSUE TITLE
支点、バネ、荷重のモデルサイズの制御ロジックを最適化

### ISSUE THREAD

**Issue by yuluji** [structuralengine/FrameWebforJS#447]

**Comment by yuluji** [comment]
現状、「支点」のモデルが小さすぎます。
モデル全体の大きさに対する比率で表示するモデルの大きさを制御していますが、モデル全体から見てもかなり小さいです。
モデルの大きさを制御するロジックを変更し、モデル全体から見ても形状が確認できるような大きさで表示できるようにしてください。

同様に、「バネ」と「荷重」についても同様のロジックに変更してください。

![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/0e953805-97d3-49d4-9998-1b8ebcc500be)
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/9e8ddbfa-7daa-47c9-8c8d-042d3565c8c2)

**Comment by namnguyen0705** [comment]
@yuluji  **I think the algorithm I will use is like this**
![image](https://github.com/structuralengine/FrameWebforJS/assets/103914919/a9aac87e-ac5c-405c-8c33-a365df6bd69a)

-	I will increase the length of the spring according to the size of the members
-	For example, at Node 4: its coordinates are in the negative number of the x axis. If the TX value is entered, I will determine the member located to its left along the Y axis. Here there will be nodes 23 and 24, the nearest node. The selected member will be 23. Member of node 23 and 4 is 3. I will take the size of member 3 as the size of the drawn spring.
**You can read more to understand**
-	Foreach all node of Support
 
![image](https://github.com/structuralengine/FrameWebforJS/assets/103914919/3783aa27-6108-437e-ab0e-f86d8b0b40b8)

-	Check the input value of each node (TX, TY)
-	If TX value -> Check whether the X coordinate is negative or positive ->  If Negative, then take the member (containing the node under consideration) with the nearest smaller coordinates with the same value of the Y axis, then take the member (containing the node under consideration) with the nearest larger coordinates with the same value of the Y axis -> Get length of the member -> Assign the obtained length to Support
-	Same with TY
**Please contact me if you have any questions**

**Comment by yuluji** [comment]
@namnguyen0705 

ありがとうございます。
一番近いメンバーの長さを参照して大きさを決める方針は2Dモードの場合、悪くないと思います。
しかし、3Dモードの場合、画像のように、モデル全体に対して短いメンバーの節点にサポートがあてられることがあり、サポートのモデルが小さくなってしまうことが危惧されます。

あなたの案に近いですが、すべての節点から一番小さい座標値(x, y, z)と一番大きい座標値(x, y, z)を取得し、その2点間の距離からサイズを設定するのはいかがでしょうか？


![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/b963c748-3981-4b93-900f-e6c392d4c158)

**Comment by namnguyen0705** [comment]
Finding the shortest X Y Z coordinates is just finding the drawing direction. Because when the button is between 2 buttons on an axis, I don't know which direction to draw. Do you have any documents about drawing the "Support"?

**Comment by yuluji** [comment]
あなたの言う通り、描画方向については最短の2点を見つける作業が必要です。
しかし、その最短2点をもとにサポートのサイズを決めるのは危険だと感じています。

サポートに関する資料を作成して送付しますね！

**Comment by yuluji** [comment]
@namnguyen0705 

サポートに関する資料をまとめました。
不足している情報があれば再度作成するのでなんでも言ってください。
[Support.pdf](https://github.com/structuralengine/FrameWebforJS/files/13275613/Support.pdf)

**Comment by namnguyen0705** [comment]
thank you!
