### ISSUE TITLE
メニューボタンと最小化ボタンが重なるときに最小化ボタンを横へずらす

### ISSUE THREAD

**Issue by yuluji** [structuralengine/FrameWebforJS#457]
ウィンドウサイズの拡大率によっては、画像のように最小化（Close）ボタンがメニューボタンと重なってしまいます。
メニューボタンと最小化ボタンが重なった場合、最小化ボタンをメニューボタンと重ならない位置まで右へずらすような処理の追加をお願いします。

![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/df49fff2-4b28-4da5-a5d0-04ff4c093326)

**Comment by namnguyen0705** [comment]
![image](https://github.com/structuralengine/FrameWebforJS/assets/103914919/cc184550-4fb5-494e-a799-28d7566496e7)
The height of the menu will exceed when zoomed in, can we use the scroll bar in this case?

**Comment by yuluji** [comment]
@namnguyen0705 
Scroll bars are good! 
Instead of moving the "Close" button to the side, please respond with a scrollbar.
However, I would like to hide the scrollbar when it is high enough, is that possible?

**Comment by namnguyen0705** [comment]
yes, you can watch my record screen
[screen-capture.webm](https://github.com/structuralengine/FrameWebforJS/assets/103914919/11e53828-4c5c-4fe4-a02d-144562791e74)

**Comment by yuluji** [comment]
Thank you Very good! 
Please create a PR when completed.

**Comment by namnguyen0705** [comment]
@yuluji this is my PR
https://github.com/structuralengine/FrameWebforJS/pull/460
