### ISSUE TITLE
デフォルト立ち上げ時にプリセットを表示させるようにする

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#467]

**Comment by yuluji** [comment]
Web版のアプリケーションに対し、機能の追加を2つお願いします。

(1) プリセット機能
「プリセット」を「ファイル」メニューに追加してください。
「プリセット」をユーザーが押すとウィンドウが出現し、任意のプレセットファイルを選ぶことができます。
プリセットファイルを選ぶとプリセットファイルが開きます。
詳しくは添付のDocumentを見てください。

(2) 起動時ポッポアップ
ユーザーがログインしているときにアプリを起動時に、ポッポアップを出現させます。
また、ユーザーがログインしていないときはプリセット内の「ラーメン高架橋」をデフォルトで開いた状態としてください。
ポッポアップには3つの選択肢があり、「Start New」「Open File」「Open Preset」です。
それぞれ、既存の機能を呼び出すことができ、例えば「Open File」を選択すると、ファイルメニューの「open file」と同じことが起きます。
詳しくは添付のDocumentを見てください。

Document
[Preset.pdf](https://github.com/structuralengine/FrameWebforJS/files/13348373/Preset.pdf)

mat-icon list
https://www.angularjswiki.com/angular/angular-material-icons-list-mat-icon-list/

Preset Files
[Preset.zip](https://github.com/structuralengine/FrameWebforJS/files/13175359/Preset.zip)
