### ISSUE TITLE
計算後のプレビューバグ(変位、支点反力、部材断面力)

### ISSUE THREAD

**Issue by murata-yuji** [structuralengine/FrameWebforJS#480]
コメントのリンクslackにjsonデータとスクショあり。（すぐ貼ります）
通常環境では再現不可能。
客先、デザリングで回線遅い（4Gで電波3本）、電源接続するも不安定な状態で発生。

**Comment by murata-yuji** [comment]
https://malme.slack.com/archives/C04KGA7MZ4M/p1697778044686289

**Comment by yuluji** [comment]
再現性が確認できたら対応
