### ISSUE TITLE
荷重の寸法表示が裏返っている

### ISSUE THREAD

**Issue by hwatanab4546** [structuralengine/FrameWebforJS#486]
サンプルデータ：[2DTest02_A.json](https://github.com/structuralengine/FrameWebforJS/files/13222184/2DTest02_A.json)

![image](https://github.com/structuralengine/FrameWebforJS/assets/95016267/b4018902-76a1-4452-adb6-56256b371228)

**Comment by yuluji** [comment]
「Load」メニューの寸法表示が裏返っているので原因調査して修正してください。
