### ISSUE TITLE
「荷重」メニューの「マーク」にポップアップを表示

### ISSUE THREAD

**Issue by yuluji** [structuralengine/FrameWebforJS#487]
「Load」メニューの「Mark」の下セルに「？」ボタンを追加し、そこへマウスのフォーカスが当たったとき、画像1枚目のようなポップアップを表示してください。
挙動については、画像二枚目にあるように、WebDanforJSの「?」ボタンと同様です。これの制御を参考にしてください。

![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/9a900773-0a80-448e-935b-2838998fcb97)
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/11d823a7-dd8d-4754-b2d4-0a0d41afe249)

ポップアップの構成画像
[mark.zip](https://github.com/structuralengine/FrameWebforJS/files/13237531/mark.zip)

**Comment by namnguyen0705** [comment]
![image](https://github.com/structuralengine/FrameWebforJS/assets/103914919/86bc49a5-dcba-4524-89cb-f9c7ce12097a)
Where will this image come from?

**Comment by yuluji** [comment]
@namnguyen0705 

これを使ってください
[mark (1).zip](https://github.com/structuralengine/FrameWebforJS/files/13263709/mark.1.zip)

**Comment by namnguyen0705** [comment]
![image](https://github.com/structuralengine/FrameWebforJS/assets/103914919/cf571a23-36dc-45a2-9f66-09bc791aeb9b)

Any model will display this?

**Comment by yuluji** [comment]
すみません、日本ではzipファイルにまとめて送る文化があって、その方法で送ってしまいました。

![01](https://github.com/structuralengine/FrameWebforJS/assets/109077766/736f712a-d550-4d95-b5f1-bf1e824082f8)
![02](https://github.com/structuralengine/FrameWebforJS/assets/109077766/4e38767f-51bd-4f3f-9375-10042fb0a7d8)
![09](https://github.com/structuralengine/FrameWebforJS/assets/109077766/386abcde-a152-4d8d-b065-b5a19eea29c7)
![11](https://github.com/structuralengine/FrameWebforJS/assets/109077766/dde131f1-dfc7-4b7c-8c9d-9158dfcac2ce)

**Comment by namnguyen0705** [comment]
@yuluji Sorry, I haven't explained clearly. What I mean is that when I hover over the dot these 4 sets of images will always be displayed and not generated or calculated from the model

**Comment by yuluji** [comment]
@namnguyen0705 
私が行いたいのは、WebDanforJSの「？」ボタンと同じように、カーソルを当てた時のみ4つの画像を表示するというものです。
これの意味は伝わっていますか？

What I want to do is to use the WebDanforJS "?" button, which displays 4 images only when the cursor is over it.
Am I communicating to you what I want to do?

https://github.com/structuralengine/FrameWebforJS/assets/109077766/5ab94009-e9c2-45bd-82ec-7fe0555144aa

**Comment by namnguyen0705** [comment]
Yes, I understand. I will get the button inside WebDanJS, when the mouse clicks on it it will display 4 images as in the description

**Comment by yuluji** [comment]
Thank you
