### ISSUE TITLE
”組合せ”の”ピックアップ”一覧に空欄の行があると、”ピックアップファイル”が出力できない

### ISSUE THREAD

**Issue by Yuzuru-Kimura** [structuralengine/FrameWebforJS#502]
Pickup file" cannot be output if there is a blank line in the "Pickup" list of "Combination".
Please investigate the cause and correct the problem.

https://github.com/structuralengine/FrameWebforJS/assets/147780035/1f1f5d6c-bbbb-4c83-a647-2581bd7e70b3

[issue502.json](https://github.com/structuralengine/FrameWebforJS/files/13495524/issue502.json)

**Comment by namnguyen0705** [comment]
How do I know if the file is in "cross-sectional force" mode?
