### ISSUE TITLE
荷重強度画面でエラー

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#54]
サンプルデータ

[default.zip](https://github.com/structuralengine/FrameWebforJS/files/5289271/default.zip)

![image](https://user-images.githubusercontent.com/4043298/94379014-8a183180-0168-11eb-8dd5-5126c4172b36.png)

**Comment by sasaco** [comment]
[Uploading エラーキャプチャ画像.zip…]()

**Comment by sasaco** [comment]
[エラーキャプチャ動画.zip](https://github.com/structuralengine/FrameWebforJS/files/5289276/default.zip)

**Comment by Masaki-beginner** [comment]
荷重の当たり判定に使っていたTHREE.CylinderGeometryの半径が小さすぎたため，エラーが発生．
1/2000を1/200に変更して，改善した．
![image](https://user-images.githubusercontent.com/59256812/94400557-4e02c200-01a4-11eb-8ee5-c3eff96f3556.png)

**Comment by Masaki-beginner** [comment]
同時に，処理速度向上のため，分布荷重で作図した矢印を削除．

**Comment by Masaki-beginner** [comment]
thickness の値が0.00005以下だと，表示不可のバグが発生．
0.00005以下の値であるとき，0.0001に変更するコードを加えて修正．

**Comment by Masaki-beginner** [comment]
同時に，分布荷重の矢印を削除することで処理速度を向上させた．
