### ISSUE TITLE
材料データの印刷に 名称が出ない

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#60]
![image](https://user-images.githubusercontent.com/4043298/138804621-a10dd5c0-11f5-407b-b18f-a0295e527833.png)

サンプルデータ
[05_FrameWeb.zip](https://github.com/structuralengine/FrameWebforJS/files/7414936/05_FrameWeb.zip)

**Comment by mizutani488** [comment]
![無題d](https://user-images.githubusercontent.com/69898951/139211016-6b642a8f-ba56-4afd-9bf3-0ce885a3e352.png)
材料名称が狭すぎる
