### ISSUE TITLE
荷重のスケーリングに不具合がある

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#60]
@Masaki-beginner 

![load](https://user-images.githubusercontent.com/4043298/95707451-89b58580-0c94-11eb-8f0d-18ebbd6542d4.gif)

**Comment by Masaki-beginner** [comment]
pointLoadScale：private関数 pointLoadResize()により，一方向のみでしかScaleの変更がされていなかった．
memberLoadScale：対応中　※groupにnameが挿入されていない

**Comment by Masaki-beginner** [comment]
memberLoadScale：荷重メッシュの作成時に，meshのup値をローカル座標軸に変換
　　　　　　　　　private関数 memberLoadResize()で，childrenのmeshを呼び出し，scaleを変更することで改善

※まだ，qzで仕様と異なる挙動を示すので，要修正
