### ISSUE TITLE
同じ荷重値なはずなのに荷重の絵が違う→計算結果に影響は出ていないか

### ISSUE THREAD

**Issue by mizutani488** [structuralengine/FrameWebforJS#61]
![S__3621062](https://user-images.githubusercontent.com/69898951/139207434-5ff82cef-9cfa-48af-adac-1df9c58f9834.jpg)

**Comment by mizutani488** [comment]
[05_FrameWeb_R1.zip](https://github.com/structuralengine/FrameWebforJS/files/7432068/05_FrameWeb_R1.zip)

**Comment by mizutani488** [comment]
65部材の終端と66部材の始端で絵が違う

**Comment by sasaco** [comment]
@Masaki-beginner 

11/5(金) これお願いします。

**Comment by Masaki-beginner** [comment]
C:\Users\odagiri\FrameWebforJS\src\app\components\three\geometry\three-load\three-load-distribute.ts
上記のコードのcreateで作られるP1とP2の大きさ関係は線形変換により作られているが、

C:\Users\odagiri\FrameWebforJS\src\app\components\three\geometry\three-load\three-load.service.ts
上記のコードのResetDataのthis.setoffsetで大きさ変換がされる、2つの荷重の大きさ関係は、円形変換により作られているため発生している。

そのため、タイトルのエラーが発生している。

2021/11/05 15:30現在、
C:\Users\odagiri\FrameWebforJS\src\app\providers\data-helper.module.ts
上記のファイルのgetScaleの円形変換を線形に修正し、対応をしている。

**Comment by sasaco** [comment]
線形に戻した
