### ISSUE TITLE
カレント行が変更されたら geometry を赤くする

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#62]
![node](https://user-images.githubusercontent.com/4043298/95708384-0d707180-0c97-11eb-8da5-3f470cc5031c.gif)

**Comment by Masaki-beginner** [comment]
three-load.service.tsのselectChangeと
three-load-○○.tsのsetColorにより，colorを変更する枠組みを作成．

materialを変更し対処
