### ISSUE TITLE
荷重の 重なりを調整

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#65]
[05_立体骨組構造解析ソフト.zip](https://github.com/structuralengine/FrameWebforJS/files/7480298/05_.zip)

![image](https://user-images.githubusercontent.com/4043298/140453599-56956c66-3e62-4cc7-891b-c43be99a9e0a.png)

↓ こうなってたい

![image](https://user-images.githubusercontent.com/4043298/140453662-370015bc-7288-4977-89a1-2a14ad29304f.png)

**Comment by sasaco** [comment]
@Masaki-beginner 

11/5(金) これお願いします。

**Comment by Masaki-beginner** [comment]
![image](https://user-images.githubusercontent.com/59256812/140489425-fe913118-fcd7-4fce-aa98-dd65b9dc5ea1.png)
self_raycasterの当たり判定条件を変更することで、修正できることが分かった。
しかし、今後も想定外の挙動をする可能性が高い。また、コードの可読性が非常に良くない。
