### ISSUE TITLE
計算結果表示部分は Html<table>タグで

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#69]
[Model00(1).zip](https://github.com/structuralengine/FrameWebforJS/files/5485498/Model00.1.zip)

**Comment by sasaco** [comment]
重すぎる

**Comment by sasaco** [comment]
@mizutani488 
タイトルが変わらない

原因わかります？

![image](https://user-images.githubusercontent.com/4043298/100961145-22fe6b00-3565-11eb-9c5f-18673be2ae39.png)

**Comment by mizutani488** [comment]
ご指摘の件でしたが、現状の最新のmasterをプルしてくる、ほかのブランチで見てみる等してみましたが、問題なく表示されるようです。もう一度プルしていただけますか？
![image](https://user-images.githubusercontent.com/69898951/100969868-2995de00-3577-11eb-935c-8e25ac60676d.png)
