### ISSUE TITLE
荷重値の差が大きい時に 小さい方の荷重が見えない

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#7]

**Comment by sasaco** [comment]
サンプルデータ
[02_FrameWeb.zip](https://github.com/structuralengine/FrameWebforJS/files/7096341/02_FrameWeb.zip)

**Comment by sasaco** [comment]
荷重の大きさ＝荷重図のスケールとしているため見にくい


対数を使うなどして、小さい荷重が小さくなりすぎないようにしてください
![image](https://user-images.githubusercontent.com/4043298/131787929-c4be1e98-0172-4011-939a-75543aa56e7c.png)

**Comment by Masaki-beginner** [comment]
円の式を用いて修正
