### ISSUE TITLE
文字は、縦横比を維持する

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#8]
![image](https://user-images.githubusercontent.com/4043298/131606557-ff4424d5-a691-4798-919c-836557ce4df5.png)

**Comment by sasaco** [comment]
サンプルデータ
[02_FrameWeb.zip](https://github.com/structuralengine/FrameWebforJS/files/7096341/02_FrameWeb.zip)

**Comment by sasaco** [comment]
Bit map フォントを使おう

**Comment by yuluji** [comment]
「荷重」の「荷重強度」内の任意のセルをクリックすると、それに対応する荷重に寸法線が表示される。
その寸法値の縦横比が1:1を維持できていないため、フォントをBit mapのものに変更してください。

**Comment by namnguyen0705** [comment]
I don't quite understand "bitmap" fonts, Is it this?
https://www.npmjs.com/package/three-bmfont-text

**Comment by yuluji** [comment]
@namnguyen0705 
I checked with Sasazawa, and apparently he investigated this issue once in December and thought that three-bmfont-text might work.
But he says he doesn't know if three-bmfont-text will work either. I am sorry, but could you take over the research and find a way to maintain the aspect ratio?

**Comment by namnguyen0705** [comment]
I still take over the research and try to add the font to Three Object 3d but to current it not working

**Comment by yuluji** [comment]
@namnguyen0705 

作業ありがとうございます。方向を「r」としたとき、下の画像のように表示が崩れてしまうので修正をお願いしたいです。
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/0a4216f7-5bfa-4fd4-8494-2b456f1f229c)

「r」の表示としては下の画像のようにしたいです。
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/df6e55bc-e76c-4fbb-833d-9a4c30fc0951)

**Comment by namnguyen0705** [comment]
@yuluji  please send for me test file

**Comment by yuluji** [comment]
@namnguyen0705 
[3DTest01_A.zip](https://github.com/structuralengine/FrameWebforJS/files/12287286/3DTest01_A.zip)

**Comment by namnguyen0705** [comment]
I fixed it in branch Namnv_#8_fix

**Comment by yuluji** [comment]
@namnguyen0705 

Thank you very much. Very good.
Please create a PR.
