### ISSUE TITLE
マウスの位置と 当たり判定の位置が ずれてる

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#9]
![sd](https://user-images.githubusercontent.com/4043298/131606682-b2be912d-0566-4bd4-a824-810e815e2b51.gif)

**Comment by sasaco** [comment]
なぜか 荷重だけ...

節点やmember は、問題ない

![sd3](https://user-images.githubusercontent.com/4043298/134758450-581ce47f-cfbc-4d51-b7d4-400e70a1a9bd.gif)

**Comment by yuluji** [comment]
@sasaco 
現在この機能切っていますが、修正しますか？

**Comment by sasaco** [comment]
困る人がいるわけじゃないので。優先順位が低いですが、マウスで選択する機能は欲しいです

**Comment by yuluji** [comment]
下記のコンポーネントでクリックしたオブジェクトを選択できる機能を開発中です。
（例えば、任意の節点をクリックすると対象のセルが選択状態となり、節点モデルは赤くなります。）
「荷重」など一部のモデルでクリックの判定がずれてしまうので修正をお願いします。
src\app\components\three\three.component.ts
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/6daf49ae-792a-41df-9cb6-46b1d3397da2)
